version: '3.7'

services:
    php-httpd:
        container_name: rtsoft_php
        build:
            context: ./docker/php
        volumes:
            - "./source:/var/www/html"
        ports:
            - 80:80
        depends_on:
            -   database
    database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            DB_HOST: ${DB_HOST}
        ports:
            - 3306:3306