FROM node:14.0.0
WORKDIR /var/www/html
CMD ["echo","######### Installing javascript packages #########"]
CMD ["npm","install"]
CMD ["echo","######### Building current development JS files #########"]
CMD ["npm","run","build-dev"]